# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/kedro-debug-runner',
                'doc_host': 'https://noklam.github.io',
                'git_url': 'https://github.com/noklam/kedro-debug-runner',
                'lib_path': 'kedro_debug_runner'},
  'syms': { 'kedro_debug_runner.core': { 'kedro_debug_runner.core.DebugRunner': ( 'blog/posts/core.html#debugrunner',
                                                                                  'kedro_debug_runner/core.py'),
                                         'kedro_debug_runner.core.DebugRunner._run': ( 'blog/posts/core.html#debugrunner._run',
                                                                                       'kedro_debug_runner/core.py'),
                                         'kedro_debug_runner.core.DebugRunner.run': ( 'blog/posts/core.html#debugrunner.run',
                                                                                      'kedro_debug_runner/core.py'),
                                         'kedro_debug_runner.core.GreedySequentialRunner': ( 'blog/posts/core.html#greedysequentialrunner',
                                                                                             'kedro_debug_runner/core.py'),
                                         'kedro_debug_runner.core.GreedySequentialRunner.run': ( 'blog/posts/core.html#greedysequentialrunner.run',
                                                                                                 'kedro_debug_runner/core.py')}}}