# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/kedro-debug-runner',
                'doc_host': 'https://noklam.github.io',
                'git_url': 'https://github.com/noklam/kedro-debug-runner',
                'lib_path': 'kedro_debug_runner'},
  'syms': {'kedro_debug_runner.core': {'kedro_debug_runner.core.foo': ('core.html#foo', 'kedro_debug_runner/core.py')}}}